server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location /c2/beacon {
        default_type image/gif;
        return 200 "GIF89a";
    }

    location /download/update.exe {
        default_type application/octet-stream;
        return 200 "FAKE-EXE";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
